Fix zuul/CI failures
Zuul check openstack-tox-py35 fails with the following error
ERROR: Package 'python-heatclient' requires a different
Python: 3.5.2 not in '>=3.6'

openstack client packages in test-requirements are only
required for func-smoke tests. Also func-smoke tests are
executed on python 2.7 environment. So the fix pins the
exact versions of openstack client packages for python 2.7.

Keystone config parameter admin-token is removed from latest
keystone charm. Remove the param from the bundle generator.

Change-Id: I657e221c43ec9807fb1886089d7068727ffb9ed9